# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Aotu.io
subtitle: 凹凸实验室
subtitle_desc: 凹凸实验室（<a href='//aotu.io' class='banner-link' target="_blank">aotu.io</a>）出品
fulltitle: 聚焦知名互联网公司、团队或站点的专业资讯APP
slogan: 阅读是维持精神呼吸的『氧』气，而『轻』意味着我们苛刻追求内容之质量

# appLink: 
appLink: https://jdc.jd.com/lab/redirect_app.html?ADTAG=o2.site.app
yingyongbaoLink: http://a.app.qq.com/o/simple.jsp?pkgname=com.aurorarn
wandoujiaLink: http://www.wandoujia.com/apps/com.aurorarn
appLinkMeetings: https://itunes.apple.com/cn/app/%E5%87%B9%E5%87%B8%E4%BC%9A%E8%AE%AE/id1248271950?mt=8
appLinkMeetingsYYB: http://sj.qq.com/myapp/detail.htm?apkName=com.aotumeeting

keywords: 轻氧, 轻氧APP, 凹凸实验室, Aotu, 前端开发, 全栈开发, IOS开发, Android开发, UED资讯, 视觉设计, 产品经理, 交互设计, 用研, 用户研究, 全栈开发
description: 凹凸实验室(aotu.io)出品的一款聚焦知名互联网公司、团队或站点的互联网资讯APP, 阅读是维持精神呼吸的『氧』气，而『轻』意味着我们苛刻追求内容之质量。在『轻氧』里你可以随时把握国内外知名互联网公司的交互、设计、前端以及开发等资讯动态信息。
author: 凹凸实验室
language: zh-cn
timezone: Asia/Shanghai
version: 1.4.0


# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://app.aotu.io
root: /
permalink: notes/:year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: notes
category_dir: cates
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - 'baidu*.html'
  - 'demo/**'
  - 'foo/**/*'

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# generator-index
index_generator:
  per_page: 24
  order_by: -date

# tag generator
## https://github.com/hexojs/hexo-generator-tag
tag_generator:
  per_page: 24

# fragments generator
## https://github.com/mamboer/hexo-generator-fragments
fragments_generator:
  dir: fragments
  per_page: 24
  index_dir: index

# Pagination
## Set per_page to 0 to disable pagination
per_page: 24
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
## fractal is inspired by https://html5up.net/fractal
theme: fractal


# Feeds
## https://www.npmjs.com/package/hexo-generator-feed
feed:
  type: atom
  path: atom.xml
  limit: false


#stylus
stylus:
  compress: false
  sourcemaps:
    comment: true
    inline: true
    sourceRoot: ''
    basePath: .


# lunr
lunr:
  field: all
  path: assets/lunr/

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  message: Super AOTUMan at {{ now('YYYY-MM-DD HH:mm:ss') }}
  repo: 
    github: git@github.com:o2team/app.git,gh-pages

# Disqus
disqus_shortname:

# Analytics
baidu_analytics: e850b980d029480b092fdd7503c3f8de
baidu_push: true
google_analytics:
at_analytics: app.aotu.io

# Social
twitter: o2circle
github:
  user: o2team
  repo: o2team.github.io

# baidu sitemap
baidusitemap:
  url: http://app.aotu.io/

# filter_cleanup
hfc_useref:
  enable: true
  concat: true

hfc_html:
  enable: true

hfc_css:
  enable: true
  exclude: 
    - '*.min.css'

hfc_js:
  enable: true
  mangle: true
  exclude: 
    - '*.min.js'

hfc_img:
  enable: false
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false

hfc_favicons:
  enable: true
  src: img/logo.png
  target: img/
  icons:
    android: true
    appleIcon: true
    appleStartup: false
    coast: false
    favicons: true
    firefox: false
    opengraph: false
    windows: true
    yandex: false

# O2 Theme Customation
logo_url: img/logo.png
